@section("header")
	@include($_SELF->_FOLDER_FRONTEND.".layouts.header")
@show
@section("main")
	@include($_SELF->_FOLDER_FRONTEND.".layouts.main")
@show
@section("footer")
	@include($_SELF->_FOLDER_FRONTEND.".layouts.footer")
@show