@section("header")
	@include($_SEFF->_FOLDER_BACKEND.".layouts.header")
@show
@section("wrapper")
	@include($_SEFF->_FOLDER_BACKEND.".layouts.main")
@show	
@section("footer")
	@include($_SEFF->_FOLDER_BACKEND.".layouts.footer")
@show